### ISSUE TITLE
SQL 1.ödev 3.soru parantez eksik 

### ISSUE THREAD

**Issue by dmrcnr** [mehmetozk4n6/patika_SQL#1]
Merhaba, SQL 1.ödev 3.soruda SQL sorgusunda AND sonrası paranteze alınmadığı için hatalı sonuç dönmüyor mu?

**Comment by mehmetozk4n6** [comment]
Evet işlem sırayla gittiğinden dolayı replacement_cost=29.99 olan değerlerin tamamını rental_rate=0.99 değerine bakmaksızın sonuca ekliyor bu yüzden hatalı sonuç dönüyor düzelttiğin için teşekkür ederim

**Comment by dmrcnr** [comment]
Rica ederim. İyi Çalışmalar.
